@baseUrl = http://localhost:8080/v1

GET {{baseUrl}}/tweets

###

POST {{baseUrl}}/tweet
Content-Type: application/json

{
    "description": "This is my Tweet"
}

###

DELETE {{baseUrl}}/tweet/1488dcb1-e73a-4f80-910e-af97c63620ad